### ISSUE TITLE
Fix spec to using luarocks

### ISSUE THREAD

**Issue by Totktonada** [tarantool/ldecnumber#2]
Please, remove 'tarantool' dependency in order to use luarocks. It has not so much sense since tarantoolctl rocks was introduced, but can help with using some old scripts, whose use luarocks with our repository.

It is follow up of https://github.com/tarantool/rocks/issues/27

**Comment by rosik** [comment]
Resolved in 003edd5a0cff1e74ffda9d9cbec40535f70e422c
